import { getPlotModule, type PlotType, type VisualizationSettings } from './visualization-studio';
export const chartAliases:Partial<Record<PlotType,string>>={bar:'柱状图 独立组比较',line:'折线图 趋势',raincloud:'云雨图 配对云雨',box:'箱线图',violin:'小提琴图',beeswarm:'蜂群图',histogram:'直方图 分布',density:'密度图',ridge:'山脊图',scatter:'散点图',correlation:'相关图',heatmap:'热图 表达矩阵','clustered-heatmap':'聚类热图','correlation-heatmap':'相关热图',pca:'主成分分析 样本相似性',pcoa:'主坐标分析',umap:'统一流形近似投影',tsne:'t-SNE降维',nmds:'非度量多维尺度',volcano:'火山图 差异表达',ma:'MA图 表达差异',enrichment:'富集气泡图 通路 GO KEGG','enrichment-bar':'富集柱图',roc:'ROC曲线 临床模型',km:'生存曲线',venn:'韦恩图 集合',upset:'集合交集图',network:'网络图',cnet:'基因通路网络',chord:'弦图',sankey:'桑基图',gsea:'基因集富集图'};
export const scenarioPresets:{id:string;en:string;zh:string;plotType:PlotType;settings?:Partial<VisualizationSettings>}[]=[
{id:'independent',en:'Independent groups',zh:'独立组比较',plotType:'bar',settings:{barInputMode:'long',barAnalysisMode:'none'}},
{id:'paired',en:'Paired change',zh:'配对变化',plotType:'raincloud',settings:{distributionShowPairedLines:true}},
{id:'paired-raincloud',en:'Paired raincloud',zh:'配对云雨',plotType:'raincloud',settings:{distributionShowPairedLines:true,showDensity:true,showPoints:true,showBox:true}},
{id:'distribution',en:'Distribution',zh:'分布',plotType:'box'},
{id:'trend',en:'Trend',zh:'趋势 折线',plotType:'line'},
{id:'differential',en:'Expression differences',zh:'表达差异',plotType:'volcano'},
{id:'enrichment',en:'External enrichment',zh:'外部富集结果',plotType:'enrichment'},
{id:'similarity',en:'Sample similarity',zh:'样本相似性',plotType:'pca'},
{id:'clinical',en:'Clinical model results',zh:'临床模型结果 ROC',plotType:'roc'},
{id:'sets',en:'Sets',zh:'集合交集',plotType:'upset'},
{id:'networks',en:'Networks',zh:'网络',plotType:'network'}];
export type CatalogEntry = PlotType | `preset:${string}`;
export function catalogPreference(values:unknown):CatalogEntry[]{
 if(!Array.isArray(values))return [];
 return [...new Set(values.filter((id):id is CatalogEntry=>typeof id==='string' && (id.startsWith('preset:')?scenarioPresets.some(preset=>`preset:${preset.id}`===id):(()=>{try{return Boolean(getPlotModule(id as PlotType));}catch{return false;}})())))].slice(0,12);
}
export function catalogEntry(id:CatalogEntry){const preset=scenarioPresets.find(preset=>`preset:${preset.id}`===id);return preset?{plotType:preset.plotType,label:`${preset.en} / ${preset.zh}`,settings:preset.settings}:{plotType:id as PlotType,label:getPlotModule(id as PlotType).definition.name,settings:undefined};}

export const plotChineseNames={
  "bar": "柱状图",
  "line": "折线图",
  "scatter": "散点图",
  "pca": "主成分分析 PCA",
  "box": "箱线图",
  "violin": "小提琴图",
  "volcano": "火山图",
  "heatmap": "热图",
  "enrichment": "富集气泡图",
  "correlation": "相关图",
  "ma": "MA 图",
  "quadrant": "象限图",
  "errorbar": "误差棒图",
  "area": "面积图",
  "lollipop": "棒棒糖图",
  "beeswarm": "蜂群图",
  "raincloud": "云雨图",
  "histogram": "直方图",
  "density": "密度图",
  "ridge": "山脊图",
  "pcoa": "主坐标分析 PCoA",
  "umap": "UMAP",
  "tsne": "t-SNE",
  "nmds": "非度量多维尺度 NMDS",
  "clustered-heatmap": "聚类热图",
  "correlation-heatmap": "相关热图",
  "enrichment-bar": "富集柱图",
  "gsea": "GSEA",
  "go-circle": "GO 环图",
  "kegg-circle": "KEGG 环图",
  "go-chord": "GO 弦图",
  "pathway-impact": "通路影响图",
  "nes-fdr": "NES／FDR 汇总",
  "multi-gsea": "多条 GSEA 曲线",
  "enrichment-ridge": "富集山脊图",
  "sankey-bubble": "关系带与气泡图",
  "geographic-map": "地理点图",
  "petal": "花瓣图",
  "word-cloud": "词云",
  "km": "Kaplan–Meier 生存曲线",
  "survival-forest": "生存森林图",
  "roc": "ROC 曲线",
  "funnel": "漏斗图",
  "precision-recall": "精确率－召回率曲线",
  "calibration": "校准曲线",
  "decision-curve": "决策曲线",
  "nomogram": "列线图",
  "lasso-path": "LASSO 路径",
  "km-cutoff": "截点 KM 图",
  "risk-score": "风险评分面板",
  "venn": "韦恩图",
  "upset": "UpSet 交集图",
  "sankey": "桑基图",
  "chord": "弦图",
  "alluvial": "冲积图",
  "ligand-receptor": "配体－受体图",
  "network": "网络图",
  "ppi": "PPI 网络",
  "cerna": "ceRNA 网络",
  "mirna-target": "miRNA－靶标图",
  "cnet": "基因－通路网络",
  "enrichment-map": "富集网络",
  "tree": "树图",
  "dendrogram": "树状聚类图",
  "circos": "Circos 图",
  "manhattan": "曼哈顿图",
  "qq": "QQ 图",
  "chromosome-ideogram": "染色体模式图",
  "snp-density": "SNP 密度",
  "genome-tracks": "基因组轨道",
  "waterfall": "突变瀑布图",
  "oncoplot": "突变谱图",
  "motif-logo": "基序标志图",
  "pie": "饼图",
  "donut": "环形图",
  "waffle": "华夫图",
  "rose": "玫瑰图",
  "treemap": "矩形树图",
  "sunburst": "旭日图",
  "radar": "雷达图",
  "polar-profile": "极坐标轮廓",
  "population-pyramid": "人口金字塔"
};
